### ISSUE TITLE
Nomad Job Spec

### ISSUE THREAD

**Issue by troyswanson** [kelseyhightower/hashiapp#1]
Hi @kelseyhightower 

Could you post the Nomad Job Spec for this repo, please? Thanks :)

PS: Thank you for your excellent talk at HashiConf 2016!

**Comment by jrasell** [comment]
@troyswanson the Nomad job files are held within https://github.com/kelseyhightower/hashiconf-eu-2016

**Comment by troyswanson** [comment]
@jrasell Thanks!
